config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"
  get "/users/login", to: "sessions#new"
  post "/users/login", to: "sessions#create"
  delete "users/:id/logout", as: "users_delete", to: "sessions#destroy"
  resources :blogs
  resource :users, except: [:index]
  get "/mypage", to: "users#show"
  resources :likes, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, presence: true
  validates :blog_id, presence: true

  belongs_to :user
  belongs_to :blog, counter_cache: :likes_count
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  
  before_validation {email.downcase!}
  validates :email, presence: true, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: {minimum: 4}
  
  has_many :blogs, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_blogs, through: :likes, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :show, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @blogs = Blog.all.order(user_id: :asc).order(id: :asc)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog.id)
    else
      flash[:danger] = "ブログの作成に失敗しました。"
      redirect_to :root
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:notice] = "ブログを更新しました。"
      redirect_to blog_path(@blog.id)
    else
      flash.now[:danger] = "ブログの更新に失敗しました。"
      render edit_users_path(@blog.id)
    end
  end

  def destroy
    @blog.destroy
    flash[:danger] = "ブログを削除しました。"
    redirect_to :root
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @blogs = current_user.like_blogs
  end
  
  def create
    @like = Like.create(user_id: current_user.id, blog_id: params[:blog_id])
    @blog = Blog.find(params[:blog_id])
    # @like = current_user.likes.create(user_id: :current_user.id, blog_id: params[:blog_id])
    # @likes = Like.find_by(blog_id: params[blog_id])
  end
  
  def destroy
    @like = Like.find(params[:id]).destroy
    @blog = Blog.find(@like.blog_id)
    # current_user.likes.find_by(blog_id: params[:blog_id]).destroy
    # @likes = Like.find_by(blog_id: params[blog_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # ■メールアドレスでログイン
    @user = User.find_by(email: params[:session][:email].downcase)
    # ログインできた場合、前のページ、もしくはブログの一覧へ。
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if session[:previous_url].nil?
        redirect_to :root
      else
        redirect_to session[:previous_url]
        session.delete(:previous_url)
      end
    # ■ログインできなかった場合、ログイン画面へ。
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました。"
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_require_login, only: [:new, :create]
  before_action :require_login, except: [:new, :create]
  before_action :set_current_user, only: [:show, :destroy, :update]
  before_action :set_params_user, only: [:create]

  def show
  end

  def new
    if params[:back]
      set_params_user
    else
      @user = User.new
    end
  end

  def create
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/mypage"
    else
      render new_users_path
    end
  end

  def edit
    if params[:back]
      overwrite_params_user
    else
      set_current_user
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "ユーザ情報を更新しました。"
      redirect_to "/mypage"
    else
      flash[:danger] = "ユーザ情報の更新に失敗しました。"
      render edit_users_path
    end
  end

  def destroy
    session.delete(:user_id)
    @user.destroy
    flash[:danger] = "ユーザを削除しました。"
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def set_current_user
    @user = current_user
  end
  def set_params_user
    @user = User.new(user_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def new_or_edit_blog_path
    blogs_path if controller.action_name == "new"
    blog_path(params[:id]) if controller.action_name == "edit"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    unless logged_in?
      session[:previous_url] = request.fullpath
      redirect_to users_login_path
    end
  end

  def not_require_login
    redirect_to :root if logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, url: new_or_edit_blog_path, local: true) do |form| %>
  <div class="form_field">
    <div class="container">
      <div class="row">
        <div class="col-md-1" id="title"><%= form.label :title, "タイトル" %></div>
        <div class="col-md-4"><%= form.text_field :title %></div>
        <div class="col-md-7"></div>
      </div>
    </div>
  </div>
  <div class="form_field">
    <div class="container">
      <div class="row">
        <div class="col-md-1" id="title"><%= form.label :content, "内容" %></div>
        <div class="col-md-4"><%= form.text_area :content, size: "50x3" %></div>
        <div class="col-md-7"></div>
      </div>
    </div>
  </div>
  
  <%= form.submit "投稿する" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>ブログの編集</h1>
<%= render "form" %>
<footer>
  <button type="button" class="btn btn-success badge-pill"><%= link_to "ブログ一覧", blogs_path %></button>
</footer>

app/views/blogs/index.html.erb
<h1>みんなのブログ一覧</h1>
<div class="container">
  <ul class="row">
    <li class="col-md-2">タイトル</li><li class="col-md-1">作者</li><li class="col-md-3">内容</li>
  </ul>
  <% @blogs.each do |b| %>
    <ul class="row">
      <li class="col-md-2"><%= link_to b.title, blog_path(b.id), method: :get %></li>
      <li class="col-md-1"><%= User.find(b.user_id).name %></li>
      <li class="col-md-3"><%= b.content[0, 10] %></li>
      <% if logged_in? %>
        <% if b.user_id == current_user.id %>
          <li class="col-md-1"><%= link_to "編集", edit_blog_path(b.id), method: :get, type: "button", class: "btn btn-default" %></li>
          <li class="col-md-1"><%= link_to "削除", blog_path(b.id), method: :delete, data: {confirm: "ブログを削除しますか。"}, type: "button", class: "btn btn-default" %></li>
          <li class="col-md-2" id="star-<%= b.id %>"><%= render partial: "likes/like", locals: {blog: b} %></li>
        <% else %>
          <li class="col-md-2 offset-md-2" id="star-<%= b.id %>"><%= render partial: "likes/like", locals: {blog: b} %></li>
        <% end %>
      <% else %>
        <td></td><td></td>
      <% end %>
    </ul>
  <% end %>
</div>

<footer>
  <button type="button" class="btn btn-success badge-pill"><%= link_to "ブログ一覧", blogs_path %></button>
</footer>

app/views/blogs/new.html.erb
<h1>ブログの作成</h1>
<%= render "form" %>
<footer>
  <button type="button" class="btn btn-success badge-pill"><%= link_to "ブログ一覧", blogs_path %></button>
</footer>

app/views/blogs/show.html.erb
<% if logged_in? %>
  <div id="star-<%= @blog.id %>"><%= render partial: "likes/like", locals: {blog: @blog} %></div>
<% end %>
<h1><%= @blog.title %></h1>
<h2><%= User.find(@blog.user_id).name %></h2>
<h2><pre><%= @blog.content %></pre></h2>

<footer>
  <button type="button" class="btn btn-success badge-pill"><%= link_to "ブログ一覧", blogs_path %></button>
  <% if logged_in? %>
    <% if @blog.user_id == current_user.id %>
      <button type="button" class="btn btn-success badge-pill"><%= link_to "編集", edit_blog_path(@blog.id), method: :get %></button>
      <button type="button" class="btn btn-success badge-pill"><%= link_to "削除", blog_path(@blog.id), method: :delete %></button>
    <% end %>
  <% end %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mine04</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <button type="button" class="btn btn-primary badge-pill"><%= link_to "トップページ", :root %></button>
        <button type="button" class="btn btn-secondary badge-pill"><%= link_to "ブログの作成", new_blog_path %></button>
        <button type="button" class="btn btn-success badge-pill"><%= link_to "お気に入り一覧", likes_path %></button>
        <button type="button" class="btn btn-info badge-pill"><%= link_to "ユーザ情報", :mypage %></button>
        <button type="button" class="btn btn-warning badge-pill"><%= link_to "ログアウト", users_delete_path(current_user.id), method: :delete %></button>
      <% else %>
        <button type="button" class="btn btn-primary badge-pill"><%= link_to "トップページ", :root %></button>
        <button type="button" class="btn btn-secondary badge-pill"><%= link_to "ログイン", users_login_path %></button>
        <button type="button" class="btn btn-info badge-pill"><%= link_to "ユーザ登録", new_users_path %></button>
      <% end %>
    </header>

    <div class="content">
      <!--■flash の表示-->
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: key) %>
      <% end %>
  
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% like = current_user.likes.find_by(blog_id: blog.id) %>
<% if like.present? %>
  <span><%= blog.likes_count %> likes  </span><%= link_to "★", like_path(like.id), method: :delete, remote: true, class: "red-star" %>
<% else %>
  <span><%= blog.likes_count %> likes  </span><%= link_to "☆", likes_path(blog_id: blog.id), method: :post, remote: true, class: "white-star" %>
<% end %>

app/views/likes/create.js.erb
$("#star-<%= @blog.id %>").html("<%= j(render partial: "like", locals: {blog: @blog})%>")

app/views/likes/destroy.js.erb
$("#star-<%= @blog.id %>").html("<%= j(render partial: "like", locals: {blog: @blog})%>")

app/views/likes/index.html.erb
<h1>お気に入りのブログ一覧</h1>
<div class="container">
  <ul class="row">
    <li class="col-md-2">タイトル</li><li class="col-md-1">作者</li><li class="col-md-3">内容</li>
  </ul>
  <% @blogs.each do |b| %>
    <ul class="row">
      <li class="col-md-2"><%= link_to b.title, blog_path(b.id), method: :get %></li>
      <li class="col-md-1"><%= User.find(b.user_id).name %></li>
      <li class="col-md-3"><%= b.content[0, 10] %></li>
      <% if logged_in? %>
        <% if b.user_id == current_user.id %>
          <li class="col-md-1"><%= link_to "編集", edit_blog_path(b.id), method: :get, type: "button", class: "btn btn-default" %></li>
          <li class="col-md-1"><%= link_to "削除", blog_path(b.id), method: :delete, data: {confirm: "ブログを削除しますか。"}, type: "button", class: "btn btn-default" %></li>
          <li class="col-md-2" id="star-<%= b.id %>"><%= render partial: "likes/like", locals: {blog: b} %></li>
        <% else %>
          <li class="col-md-2 offset-md-2" id="star-<%= b.id %>"><%= render partial: "likes/like", locals: {blog: b} %></li>
        <% end %>
      <% else %>
        <td></td><td></td>
      <% end %>
    </ul>
  <% end %>
</div>

<footer>
  <button type="button" class="btn btn-success badge-pill"><%= link_to "ブログ一覧", blogs_path %></button>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
<!--■エラーの表示。-->
  <% if @user.errors.any? %>
    <div class="errors">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--■ここから入力。-->
  <div class="form_field">
    <%= form.label :name, "名前" %>
    <%= form.text_field :name %>
  </div>
  <div class="form_field">
    <%= form.label :email, "メールアドレス" %>
    <%= form.email_field :email %>
  </div>
  <div class="form_field">
    <%= form.label :password, "パスワード" %>
    <%= form.password_field :password %>
  </div>
  <div class="form_field">
    <%= form.label :password_confirmation, "パスワード確認" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit "ユーザ登録" %>
  <%= link_to "戻る", :back, type: "button", class: "btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ編集画面</h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1>ユーザ登録画面</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1>ユーザ画面</h1>
<p>名前： <%= @user.name %></p>
<p>メールアドレス： <%= @user.email %></p>
<%= link_to "ブログ一覧", :root, type: "button", class: "btn btn-default" %>
<%= link_to "ユーザ編集", edit_users_path, type: "button", class: "btn btn-default" %>
<%= link_to "ユーザ削除", users_path, method: "delete", data:{confirm: "ユーザを削除しますか？"}, type: "button", class: "btn btn-default" %>